[tool.poetry]
name = "kobold-legacy"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
discord2 = "^2.0.1"
discord = "^1.7.3"
python-dotenv = "^0.20.0"
pip = "^22.1.2"

[tool.poetry.dev-dependencies]
toml = {version = "^0.10.2", optional = true}
yapf = {version = "^0.32.0", optional = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
