[tool.poetry]
name = "kobold-legacy"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.20.0"
pip = "^22.1.2"
py-cord = "^2.0.0"

[tool.poetry.dev-dependencies]
toml = {version = "^0.10.2", optional = true}
yapf = {version = "^0.32.0", optional = true}
pre-commit = {version = "^2.20.0", optional = true}
jupyter = {version = "^1.0.0", optional = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Import sorter
[tool.isort]
src_paths = ["src", "tests"]
combine_as_imports=true
combine_star=true
float_to_top=true
remove_redundant_aliases=true
balanced_wrapping=true

# Import cleaner
[tool.pycln]
expand_stars=true
