select = [
	"F",     # Pyflakes
	"E",     # pycodestyle errors
	"W",     # pycodestyle warnings
	"I",     # isort
	"N",     # pep8-naming
	"UP",    # pyupgrade
	"ASYNC", # flake8-async
	"B",     # flake8-bugbear
	"C4",    # flake8-comprehensions
	"FA",    # flake8-future-annotations
	"ISC",   # flake8-implicit-str-concat 
	"ICN",   # flake8-import-conventions
	"PIE",   # flake8-pie           # Misc. unneeded or duplicated elements
	"TCH",   # flake8-type-checking # libraries only invoked for type annotations
	"INT",   # flake8-gettext 
	"PTH",   # flake8-use-pathlib   # Use pathlib over os/inbuilt
	"TRY",   # tryceratops          # Exceptions
	"FLY",   # flynt                # str join alternatives
	"RUF",   # Ruff-specific rules
]
ignore = [
	"E501", # "Line too long"; if Black doesn't fix it, we don't really care
	"E741", # "Ambiguous variable name"; will need fixing once we understand the code throughly; a bunch of "_l" is not better.
]
