select = [
	"F",     # Pyflakes
	"UP",    # pyupgrade
	"ASYNC", # flake8-async
	"B",     # flake8-bugbear
	"C4",    # flake8-comprehensions
	"FA",    # flake8-future-annotations
	"ISC",   # flake8-implicit-str-concat 
	"PIE",   # flake8-pie           # Misc. unneeded or duplicated elements
	"TCH",   # flake8-type-checking # libraries only invoked for type annotations
	"INT",   # flake8-gettext 
	"PTH",   # flake8-use-pathlib   # Use pathlib over os/inbuilt
	"TRY",   # tryceratops          # Exceptions
	"FLY",   # flynt                # str join alternatives
	"RUF",   # Ruff-specific rules
]
