select = [
	"F",     # Pyflakes
	"E",     # pycodestyle errors
	"W",     # pycodestyle warnings
	"I",     # isort
	"N",     # pep8-naming
	"UP",    # pyupgrade
	"ASYNC", # flake8-async
	"B",     # flake8-bugbear
	"A",    # flake8-builtins
	"C4",    # flake8-comprehensions
	"FA",    # flake8-future-annotations
	"ISC",   # flake8-implicit-str-concat 
	"ICN",   # flake8-import-conventions
	"PIE",   # flake8-pie           # Misc. unneeded or duplicated elements
	"RET",   # flake8-return
	"SIM",   # flake8-simplify
	"TID",   # flake8-tidy-imports
	"TCH",   # flake8-type-checking # libraries only invoked for type annotations
	"INT",   # flake8-gettext 
	"PTH",   # flake8-use-pathlib   # Use pathlib over os/inbuilt
	"PL",    # Pylint 
	"TRY",   # tryceratops          # Exceptions
	"FLY",   # flynt                # str join alternatives
	"PERF",  # Perflint 
	"RUF",   # Ruff-specific rules
]

include = ["*.py", "*.pyi", "pyproject.toml", "rust.toml"]
ignore = [
	"E501",    # "Line too long"; if Black doesn't fix it, we don't really care
	"PLW2901", # `for` loop variable overwritten by assignment target; not really important

	# To fix, eventually:
	"E741",    # "Ambiguous variable name"; will need fixing once we understand the code thoroughly; a bunch of "_l" is not better.
	"PLR0912", # Too many branches
	"PLR0915", # Too many statements
	"PLR0911", # Too many return statements
	"PLR0913", # Too many arguments to function call
	"PLR2004", # Magic value used in comparison, consider replacing 10 with a constant variable  
	"PLW0602", # global-variable-not-assigned / one half is false positives, the other half needs understanding
	"PLW0603", # Using the global statement to update `action_queue` is discouraged
]
target-version = "py38"
isort.force-single-line = true
